#!/bin/bash
set -e
TOOLS_VERSION="1.1"

command -v curl >/dev/null 2>&1 || { echo >&2 "curl not found!  Please install curl."; exit 1; }
INIT=`curl -q https://wwwin-github.cisco.com/raw/smi-build/build-tools/$TOOLS_VERSION/_init 2> /dev/null`
eval "$INIT"