apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ss-cert-provisioner-{{ .Release.Name }}-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ss-cert-provisioner-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ss-cert-provisioner-{{ .Release.Name }}-binding
roleRef:
  kind: ClusterRole
  name: ss-cert-provisioner-{{ .Release.Name }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ss-cert-provisioner-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-cert-provisioner
  labels:
    component: ss-cert-provisioner
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: ss-cert-provisioner
  template:
    metadata:
      labels:
        name: ss-cert-provisioner
    spec:
      serviceAccountName: ss-cert-provisioner-sa
      securityContext:
{{ toYaml .Values.global.securityContext | indent 8 }}
      containers:
      - name: cert-monitor
        image: {{.Values.global.registry}}{{ .Values.images.cert_monitor }}
        command:
          - /usr/local/bin/cert-monitor.py
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        {{ if not $.Values.global.singleNode }}
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "200m"
        {{ end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if eq .Values.global.singleNode false }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: smi.cisco.com/node-type
                operator: In
                values:
                - oam
      {{- end }}
